# Generated by Django 3.2.6 on 2023-11-01 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(upload_to='csvs/')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('impression_city', models.CharField(max_length=255)),
                ('posting_user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('viewer_email', models.EmailField(max_length=255)),
                ('impression_country', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('device', models.CharField(max_length=255)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='csvapp.csvfile')),
            ],
        ),
    ]
