# Generated by Django 3.2.6 on 2023-11-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impression',
        ),
    ]
